[package]
name = "rust-bff"
version = "0.1.0"
authors = ["Hoshi <hoshimure.47@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
openssl = "0.10.28"
